# Generated by Django 3.2.7 on 2021-11-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome', max_length=100)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('telefone', models.CharField(help_text='Telefone com DDD e DDI', max_length=20)),
                ('dtNasc', models.DateField(help_text='Nascimento no formado DD/MM/AAAA', verbose_name='Data de Nascimento')),
                ('cidade', models.CharField(help_text='Cidade', max_length=254)),
                ('estado', models.CharField(help_text='Estado', max_length=254)),
                ('pais', models.CharField(help_text='País', max_length=254)),
                ('descricao', models.CharField(help_text='Descrição', max_length=254)),
                ('experiencia', models.CharField(help_text='Experiências', max_length=254)),
                ('formacao', models.CharField(help_text='Formação', max_length=254)),
                ('cargo', models.CharField(help_text='Cargo', max_length=254)),
                ('estadoCivil', models.CharField(help_text='Estado civil', max_length=254)),
                ('sexo', models.CharField(help_text='Sexo', max_length=254)),
                ('endereco', models.CharField(help_text='Endereco', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome', max_length=100)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('telefone', models.CharField(help_text='Telefone com DDD e DDI da empresa', max_length=20)),
                ('endereco', models.CharField(help_text='Endereço', max_length=254)),
                ('descricao', models.CharField(help_text='Descrição', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(help_text='Usuario', max_length=100)),
                ('senha', models.CharField(help_text='Senha', max_length=100)),
                ('tipo', models.CharField(choices=[('EMPRESA', 'Empresa'), ('CANDIDATO', 'Candidato')], max_length=10)),
            ],
        ),
    ]
