# Generated by Django 3.2.9 on 2021-11-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrabalhoWeb', '0002_alter_candidato_dtnasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='dtNasc',
            field=models.DateField(help_text='Nascimento no formado DD/MM/AAAA', verbose_name='Data de Nascimento'),
        ),
    ]
