# Generated by Django 3.2.9 on 2021-11-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrabalhoWeb', '0007_auto_20211128_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
