# Generated by Django 3.2.9 on 2021-11-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrabalhoWeb', '0010_auto_20211128_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='dtNasc',
            field=models.CharField(help_text='Nascimento no formado DD/MM/AAAA', max_length=254, verbose_name='Data de Nascimento'),
        ),
    ]
