# Generated by Django 3.2.7 on 2021-11-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrabalhoWeb', '0008_auto_20211128_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='id',
        ),
        migrations.AddField(
            model_name='candidato',
            name='usuario',
            field=models.CharField(default=1, help_text='Usuario', max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
